In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.cluster import DBSCAN, KMeans
from sklearn.compose import make_column_transformer
from sklearn.datasets import load_sample_image, make_blobs
from sklearn.decomposition import PCA
from sklearn.ensemble import BaggingClassifier, BaggingRegressor, GradientBoostingClassifier, GradientBoostingRegressor, RandomForestClassifier, RandomForestRegressor, StackingClassifier, StackingRegressor
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.inspection import permutation_importance
from sklearn.linear_model import Lasso, LinearRegression, LogisticRegression, Ridge
from sklearn.manifold import Isomap, LocallyLinearEmbedding, MDS
from sklearn.metrics import auc, confusion_matrix, ConfusionMatrixDisplay, davies_bouldin_score, rand_score, roc_auc_score, roc_curve, silhouette_samples, silhouette_score 
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, PolynomialFeatures, StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, plot_tree
import statsmodels.api as sm

<h1>Variante 1 "Garnichts machen" </h1>

In [2]:
df1 = pd.read_csv('v1_data_dog_normal.csv')
df1.head()

size_dog  eye_circularity  skull_circularity  ear_size  eyes_distance  \
0      95.0             48.0               83.0     178.0           72.0   
1      91.0             41.0               84.0     141.0           57.0   
2     104.0             50.0              106.0     209.0           66.0   
3      93.0             41.0               82.0     159.0           63.0   
4      85.0             44.0               70.0     205.0          103.0   

   ear_form  hair_tone  nose_elongatedness  weight_dog  muzzle_form  \
0      10.0      162.0                42.0        20.0        159.0   
1       9.0      149.0                45.0        19.0        143.0   
2      10.0      207.0                32.0        23.0        158.0   
3       9.0      144.0                46.0        19.0        143.0   
4      52.0      149.0                45.0        19.0        144.0   

   skin_tone_main  skin_pattern_complexity  body_length  tail_length  \
0           176.0                    379.0        184.0         70.0   
1           170.0                    330.0        158.0         72.0   
2           223.0                    635.0        220.0         73.0   
3           160.0                    309.0        127.0         63.0   
4           241.0                    325.0        188.0        127.0   

   hair_curlness  hair_length  leg_front_number  leg_back_number  \
0            6.0         16.0             187.0            197.0   
1            9.0         14.0             189.0            199.0   
2           14.0          9.0             188.0            196.0   
3            6.0         10.0             199.0            207.0   
4            9.0         11.0             180.0            183.0   

              breuni_class  
0  fashion_lifestyle_elite  
1  fashion_lifestyle_elite  
2              main_stream  
3  fashion_lifestyle_elite  
4                   trendy

In [3]:
dogStr_df = df1[['breuni_class']]
dogStr_df.head()

breuni_class
0  fashion_lifestyle_elite
1  fashion_lifestyle_elite
2              main_stream
3  fashion_lifestyle_elite
4                   trendy

In [4]:
dogNoStr_df = df1.drop(columns='breuni_class')
dogNoStr_df.head()

size_dog  eye_circularity  skull_circularity  ear_size  eyes_distance  \
0      95.0             48.0               83.0     178.0           72.0   
1      91.0             41.0               84.0     141.0           57.0   
2     104.0             50.0              106.0     209.0           66.0   
3      93.0             41.0               82.0     159.0           63.0   
4      85.0             44.0               70.0     205.0          103.0   

   ear_form  hair_tone  nose_elongatedness  weight_dog  muzzle_form  \
0      10.0      162.0                42.0        20.0        159.0   
1       9.0      149.0                45.0        19.0        143.0   
2      10.0      207.0                32.0        23.0        158.0   
3       9.0      144.0                46.0        19.0        143.0   
4      52.0      149.0                45.0        19.0        144.0   

   skin_tone_main  skin_pattern_complexity  body_length  tail_length  \
0           176.0                    379.0        184.0         70.0   
1           170.0                    330.0        158.0         72.0   
2           223.0                    635.0        220.0         73.0   
3           160.0                    309.0        127.0         63.0   
4           241.0                    325.0        188.0        127.0   

   hair_curlness  hair_length  leg_front_number  leg_back_number  
0            6.0         16.0             187.0            197.0  
1            9.0         14.0             189.0            199.0  
2           14.0          9.0             188.0            196.0  
3            6.0         10.0             199.0            207.0  
4            9.0         11.0             180.0            183.0

<h1>Variante 2 "PCA mit Standardisierung" </h1>

In [5]:
pca2= make_pipeline(
    StandardScaler(),PCA(n_components=18)
    
)
pca2.fit_transform(dogNoStr_df)
pca2['pca'].explained_variance_ratio_

array([5.23842715e-01, 1.67922206e-01, 1.05489449e-01, 6.54626098e-02,
       5.07963290e-02, 2.96175664e-02, 1.97685972e-02, 1.22336746e-02,
       8.76239809e-03, 5.05408102e-03, 3.50247758e-03, 2.44109126e-03,
       1.94607302e-03, 1.18993618e-03, 8.85813314e-04, 7.20022354e-04,
       3.44709645e-04, 2.02501932e-05])

In [6]:
pca2['pca'].components_

array([[ 2.74831771e-01,  2.95010714e-01,  3.04449087e-01,
         2.67736007e-01,  8.05023115e-02,  9.67344418e-02,
         3.16974201e-01, -3.13578155e-01,  3.13919564e-01,
         2.82333728e-01,  3.09412520e-01,  3.14367158e-01,
         2.71718519e-01, -2.11828921e-02,  4.14663527e-02,
         5.76364277e-02,  2.94889050e-02,  7.35592120e-02],
       [-1.27658782e-01,  1.30073139e-01, -7.48089621e-02,
        -1.88895631e-01, -1.21175308e-01,  1.10227254e-02,
         4.71040360e-02,  1.33882597e-02,  5.99504212e-02,
         1.15678806e-01,  6.19071507e-02,  5.16105865e-02,
         2.08657818e-01,  4.89069068e-01, -5.70936548e-02,
        -1.24691532e-01, -5.40654749e-01, -5.39434552e-01],
       [-1.19287990e-01, -2.99793011e-02, -5.54364072e-02,
         2.74808687e-01,  6.42808859e-01,  5.92125977e-01,
        -9.63548068e-02,  5.65554126e-02, -1.09164899e-01,
        -1.70186147e-02,  5.67570534e-02, -1.07764904e-01,
        -3.12995047e-02,  2.85044378e-01, -1.15755322e

In [7]:
pca2= make_pipeline(
    StandardScaler(),PCA(n_components=5)
    
)
pca2.fit_transform(dogNoStr_df)
pca2['pca'].explained_variance_ratio_

array([0.52384272, 0.16792221, 0.10548945, 0.06546261, 0.05079633])

In [8]:
df2 = pd.DataFrame(pca2.fit_transform(dogNoStr_df))
df2['breuni_class'] = dogStr_df
df2.head()

0         1          2         3         4             breuni_class
0  0.329746 -0.215835   0.997248  0.171485  0.081947  fashion_lifestyle_elite
1 -1.594478 -0.422979  -0.370002  0.231497  0.691322  fashion_lifestyle_elite
2  3.760799  0.186851   0.087971  1.202770  0.729704              main_stream
3 -1.742311 -2.825632   0.111181  0.374927 -0.370714  fashion_lifestyle_elite
4  0.549668  4.764098  11.689234  0.163830  3.257210                   trendy

In [9]:
df2.to_csv(r'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt\v2_data_dog_PCA+standardized.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt'

<h1>Variante 3 "PCA ohne Standardisierung" </h1>

In [10]:
pca3 = PCA(n_components=18)

In [11]:
pca3.fit_transform(dogNoStr_df)
pca3.explained_variance_ratio_

array([9.59254724e-01, 1.79839369e-02, 1.19578103e-02, 3.93789057e-03,
       1.96638556e-03, 1.33164194e-03, 1.14732207e-03, 7.72773169e-04,
       6.25803575e-04, 3.26260692e-04, 2.59883176e-04, 1.63508071e-04,
       1.29184631e-04, 6.82487246e-05, 4.65151738e-05, 1.93942985e-05,
       6.73580871e-06, 1.98111044e-06])

1. 95,92%
2. 1,79%
3. 1,19%
4. 0,39%

In [12]:
pca3 = PCA(n_components=2)

In [13]:
df3 = pd.DataFrame(pca3.fit_transform(dogNoStr_df))
df3['breuni_class'] = dogStr_df
df3.head()

0          1             breuni_class
0  -57.332839  12.411256  fashion_lifestyle_elite
1 -116.911811  -9.414613  fashion_lifestyle_elite
2  211.526976   7.911040              main_stream
3 -141.291488  20.490169  fashion_lifestyle_elite
4  -98.423682  50.854161                   trendy

In [14]:
df3.to_csv(r'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt\v3_data_dog_PCA-standardized.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt'

<h1>Variante 4 "Kohonen-Maps" </h1>

In [18]:
df4 = pd.read_csv('v4_data_dog_KM.csv')
df4 = df4.drop(columns="Unnamed: 0")
df4['breuni_class'] = dogStr_df
df4.head()

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
df4.to_csv(r'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt\v4_data_dog_KM.csv', index=False)

: 

In [20]:
df4 = pd.read_csv('v4_data_dog_KM.csv')
df4.head()

data_to_neuron  neuron_to_neighbour             breuni_class
0        0.255732             0.314266  fashion_lifestyle_elite
1        0.234393             0.314266  fashion_lifestyle_elite
2        0.195993             0.314266              main_stream
3        0.354151             0.314266  fashion_lifestyle_elite
4        0.305593             0.314266                   trendy

<h1>Variante 5 "Iso-Maps" </h1>

In [21]:
iso = Isomap(n_components=2)
df5 = pd.DataFrame(iso.fit_transform(dogNoStr_df))
df5['breuni_class'] = dogStr_df
df5.head()

c:\Users\Projektbenutzer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\manifold\_isomap.py:348: UserWarning: The number of connected components of the neighbors graph is 2 > 1. Completing the graph to fit Isomap might be slow. Increase the number of neighbors to avoid this issue.
  self._fit_transform(X)
c:\Users\Projektbenutzer\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\sparse\_index.py:103: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])


0           1             breuni_class
0  -80.468076   63.178497  fashion_lifestyle_elite
1 -182.920855   26.859518  fashion_lifestyle_elite
2  320.533431   42.077580              main_stream
3 -209.535514  -28.682925  fashion_lifestyle_elite
4 -263.714362  181.862334                   trendy

In [22]:
df5.to_csv(r'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt\v5_data_dog_IsoMaps.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt'

<h1>Variante 6 "Locally Linear Embedding" </h1>

In [23]:
lle = LocallyLinearEmbedding(n_components=2)
df6 = pd.DataFrame(lle.fit_transform(dogNoStr_df))
df6['breuni_class'] = dogStr_df
df6.head()

0         1             breuni_class
0  0.034879  0.023579  fashion_lifestyle_elite
1  0.034879  0.024867  fashion_lifestyle_elite
2  0.034879 -0.053069              main_stream
3  0.034879  0.025725  fashion_lifestyle_elite
4  0.034879  0.022910                   trendy

In [24]:
df6.to_csv(r'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt\v6_data_dog_LLE.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'C:\Users\nwbab\OneDrive\Dokumente\GitHub\Kohonen-maps_Projekt'